>>> z[4]                                                                        
Traceback (most recent call last):                                              
  File "<stdin>", line 1, in <module>                                           
IndexError: list index out of range                                             
